camera_spin_duration: 600 # In seconds

jobs:

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
      - filename: bpfland-defaults.csv
        scheduler: release/scx_bpfland
      - filename: bpfland-c0-t0-k.csv
        scheduler: release/scx_bpfland -c 0 -t 0 -k

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_lavd/
      cmd: cargo build --release
    runs:
      - filename: lavd-defaults.csv
        scheduler: release/scx_lavd

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_rusty/
      cmd: cargo build --release
    runs:
      - filename: rusty-defaults.csv
        scheduler: release/scx_rusty

  - reset_to: origin/asdf
    build:
      dir: scheds/rust/scx_asdf/
      cmd: cargo build --release
    runs:
      - filename: asdf-defaults.csv
        scheduler: release/scx_asdf
