camera_spin_duration: 300 # In seconds

# Specify background load task
background_load: stress -c 8

jobs:

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
      - filename: bpfland-defaults.csv
        scheduler: release/scx_bpfland

      # Empty like this - just won't start anything, so eventually uses BORE :)
      - filename: bore.csv

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_rustland/
      cmd: cargo build --release
    runs:
      - filename: rustland-defaults.csv
        scheduler: release/scx_rustland

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_flash/
      cmd: cargo build --release
    runs:
      - filename: flash-defaults.csv
        scheduler: release/scx_flash

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_lavd/
      cmd: cargo build --release
    runs:
      - filename: lavd-defaults.csv
        scheduler: release/scx_lavd

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_rusty/
      cmd: cargo build --release
    runs:
      - filename: rusty-defaults.csv
        scheduler: release/scx_rusty

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_p2dq/
      cmd: cargo build --release
    runs:
      - filename: p2dq-defaults.csv
        scheduler: release/scx_p2dq

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_wd40/
      cmd: cargo build --release
    runs:
      - filename: p2dq-defaults.csv
        scheduler: release/scx_wd40
