camera_spin_duration: 600 # In seconds

jobs:

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
     - filename: bpfland.csv
       scheduler: release/scx_bpfland
     - filename: bore.csv

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_lavd/
      cmd: cargo build --release
    runs:
     - filename: lavd.csv
       scheduler: release/scx_lavd

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_rustland/
      cmd: cargo build --release
    runs:
     - filename: rustland.csv
       scheduler: release/scx_rustland

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_rusty/
      cmd: cargo build --release
    runs:
     - filename: rusty.csv
       scheduler: release/scx_rusty
