camera_spin_duration: 60

jobs:

  - branch: main
    build:
      dir: scheds/rust/scx_lavd/
      cmd: cargo build --release
    runs:
      - filename: lavd-defaults.csv
        scheduler: release/scx_lavd
