camera_spin_duration: 15 # In seconds

jobs:
  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
      - filename: bpfland-defaults-__SCH__.csv
        scheduler: release/scx_bpfland
