camera_spin_duration: 600 # In seconds

jobs:

  - reset_to: pr/509
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
      - filename: bpfland-pr509.csv
        scheduler: release/scx_bpfland

  - reset_to: origin/main
    build:
      dir: scheds/rust/scx_bpfland/
      cmd: cargo build --release
    runs:
      - filename: bpfland-main.csv
        scheduler: release/scx_bpfland
