name: Benchmark
run-name: Benchmark ${{ github.event.inputs.benchmark_file }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      benchmark_file:
        description: 'Select benchmark definition file'
        required: true
        default: 'all_idle.yml'
        type: choice
        options:
          - all_idle.yml
          - all_busy.yml
          - dev.yml
          - bpfland_vs_bpfland-next.yml
          - bpfland_vs_bpfland-next-load.yml
          - last_5_commits.yml
          - specific_commits.yml

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]

    env:
      # Get using: ps aux | grep 'steamapps\\common'
      GAME_EXEC: FactoryGameSteam-Win64-Shipping.exe

      # Where to pull & compile SCX repo. Works as cache, so use persistent storage
      SCX_DIR: /var/lib/github-actions/scx

      # Where to compile SCX artifacts. Works as cache, so use persistent storage
      CARGO_TARGET_DIR: /var/lib/github-actions/scx-cargo-target

      # Where mangohud stores its benchmark data. Script will mess with permissions, so use
      # a dedicated folder and NOT anything like home directory.
      BENCHMARKS_DIR: /tmp/mangohud_logs

      # User that runs the game. Cannot be root user.
      GAME_USER: deck

      # Game's name (used for benchmark title when uploading)
      GAME_NAME: Satisfactory

      # Target URL for uploading benchmark data
      BASE_URL: https://flightlesssomething-auto.ambrosia.one

      # Do not edit these
      MYSESSION: ${{ secrets.MYSESSION }}
      JOB_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Benchmark game
        run: bash benchmark.sh "benchmarks/${{ github.event.inputs.benchmark_file }}"

      - name: Upload results
        run: bash upload.sh
