name: Benchmark CP2077

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:

      - name: Check if Cyberpunk 2077 is not running
        run: pgrep -f 'Cyberpunk2077.exe' > /dev/null

      - name: Unfreeze the game
        run: sudo kill -CONT $(pgrep -f 'Cyberpunk2077.exe')

      - name: Ensure dotool pipe has needed permissions
        run: sudo chown $USER /tmp/dotool-pipe

      - name: Ensure /tmp/mangohud_logs exist
        run: |
          sudo mkdir -p /tmp/mangohud_logs
          sudo chmod -R 777 /tmp/mangohud_logs/

      - name: Cleanup from previous jobs
        run: |
          sudo chmod 777 /tmp/mangohud_logs/*
          rm -f /tmp/mangohud_logs/*

    ###########################################################################

      - name: Download this repo
        uses: actions/checkout@v4

      - name: Build and run benchmark
        run: chmod +x benchmark.sh && ./benchmark.sh benchmark.yml

      - name: Show recorded benchmark files
        run: |
          sudo chmod 777 /tmp/mangohud_logs/*
          ls -l /tmp/mangohud_logs/*

      - name: Upload benchmark to FlightlessSomething auto
        run: chmod +x upload.sh && ./upload.sh ${{ secrets.MYSESSION }}

    ###########################################################################

      - name: Freeze the game
        run: sudo kill -STOP $(pgrep -f 'Cyberpunk2077.exe')
