name: Benchmark BG3

on:
  workflow_dispatch:
    inputs:
      benchmark_file:
        description: 'Select benchmark definition file'
        required: true
        default: 'all_idle.yml'
        type: choice
        options:
          - all_busy.yml
          - erkexzcx.yml
          - all_idle.yml
          - arighi1.yml
          - arighi2.yml
          - last_commits.yml
          - specific_commits.yml
      description:
        description: 'Additional comment for this benchmark'
        required: true
        default: 'Manually triggered benchmark'
      noupload:
        description: "(Advanced) Check to disable auto upload"
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'

jobs:
  benchmark:
    name: BG3 benchmark, ${{ github.event.inputs.benchmark_file }}, ${{ github.event.inputs.description }}
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:
      - name: Download this repo
        uses: actions/checkout@v4

      - name: Build and run benchmark
        run: chmod +x benchmark.sh && ./benchmark.sh "benchmarks/${{ github.event.inputs.benchmark_file }}"

      - name: Show recorded benchmark files
        run: |
          sudo chmod 777 /tmp/mangohud_logs/*
          ls -l /tmp/mangohud_logs/*

      - name: Upload benchmark to FlightlessSomething auto
        if: ${{ inputs.noupload == 'false' }}
        run: |
          JOBURL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          chmod +x upload.sh && ./upload.sh ${{ secrets.MYSESSION }} "$JOBURL" "${{ github.event.inputs.description }}"

      - name: Copy benchmark to persistent storage
        if: ${{ inputs.noupload == 'true' }}
        run: |
          ts=$(date +%s)
          echo "/home/deck/persistent_runs/$ts"
          sudo mkdir -p /home/deck/persistent_runs/
          sudo cp -r /tmp/mangohud_logs/*.csv "/home/deck/persistent_runs/$ts/"
