name: Benchmark CP2077

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:

      - name: Check if Cyberpunk 2077 is not running
        run: pgrep -f 'Cyberpunk2077.exe' > /dev/null

      - name: Unfreeze the game
        run: sudo kill -CONT $(pgrep -f 'Cyberpunk2077.exe')

      - name: Ensure dotool pipe has needed permissions
        run: |
          sudo chown $USER /tmp/dotool-pipe

      - name: Checkout
        uses: actions/checkout@v4

###########################################################################

      - name: Cleanup from previous run
        run: |
          rm -f /tmp/mangohud_logs/*

      - name: Record benchmark
        run: |
          # Wake up from sleep (e.g. screen is off)
          echo mousemove 2500 0 | dotoolc
          sleep 1

          # Do MangoHud benchmark
          echo keydown shift+f2 | dotoolc && sleep 0.2 && echo keyup shift+f2 | dotoolc # Start recording
          for i in {1..100}; do echo mousemove 1000 0 | dotoolc; sleep 0.1; done
          echo keydown shift+f2 | dotoolc && sleep 0.2 && echo keyup shift+f2 | dotoolc # Stop recording

          # Wait for things to settle down
          sleep 0.5

      - name: Show recorded benchmark files
        run: |
          rm -f /tmp/mangohud_logs/*summary.csv
          mv /tmp/mangohud_logs/*.csv /tmp/mangohud_logs/benchmark.csv

      - name: Upload benchmark
        run: |
          chmod +x upload.sh && ./upload.sh ${{ secrets.MYSESSION }}

###########################################################################

      - name: Freeze the game
        run: sudo kill -STOP $(pgrep -f 'Cyberpunk2077.exe')
