name: Benchmark CP2077

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    env:
      YDOTOOL_SOCKET: /run/user/1000/.ydotool_socket
    steps:

      - name: Check if Cyberpunk 2077 is not running
        run: pgrep -f 'Cyberpunk2077.exe' > /dev/null

      - name: Unfreeze the game
        run: sudo kill -CONT $(pgrep -f 'Cyberpunk2077.exe')

      - name: Ensure ydotool socket is accessible
        run: |
          sudo chmod +x /run/user/1000
          sudo chmod 777 /run/user/1000/.ydotool_socket

###########################################################################

      - name: Test ydotool command
        run: |
          # Cleanup
          sudo rm -f /home/deck/mangohud_logs/*

          ydotool mousemove 2500 0
          sleep 1
          ydotool key 42:1 68:1 68:0 42:0 #Shift_L+F2 - Start recording
          for i in {1..50}; do ydotool mousemove 2500 0; sleep 0.2; done
          ydotool key 42:1 68:1 68:0 42:0 #Shift_L+F2 - Stop recording

          # Show what is recorded
          sudo rm -f /home/deck/mangohud_logs/*summary.csv
          sudo ls -l /home/deck/mangohud_logs/*.csv

###########################################################################

      - name: Freeze the game
        run: sudo kill -STOP $(pgrep -f 'Cyberpunk2077.exe')
