name: Benchmark BG3

on:
  workflow_dispatch:
    inputs:
      benchmark_file:
        description: 'Select benchmark definition file'
        required: true
        default: 'all_idle.yml'
        type: choice
        options:
          - all_busy.yml
          - erkexzcx.yml
          - all_idle.yml
          - last_commits.yml
          - specific_commits.yml
      description:
        description: 'Additional comment for this benchmark'
        required: true
        default: 'Manually triggered benchmark'

jobs:
  benchmark:
    name: BG3 benchmark, ${{ github.event.inputs.benchmark_file }}, ${{ github.event.inputs.description }}
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:

      - name: Check if game is not running
        run: pgrep -f 'bg3.exe' > /dev/null

      - name: Ensure dotool pipe has needed permissions
        run: sudo chown $USER /tmp/dotool-pipe

      - name: Ensure /tmp/mangohud_logs exist and is empty
        run: |
          sudo rm -rf /tmp/mangohud_logs
          sudo mkdir -p /tmp/mangohud_logs
          sudo chmod -R 777 /tmp/mangohud_logs/

      - name: Download this repo
        uses: actions/checkout@v4

      - name: Build and run benchmark
        run: chmod +x benchmark.sh && ./benchmark.sh "benchmarks/${{ github.event.inputs.benchmark_file }}"

      - name: Show recorded benchmark files
        run: |
          sudo chmod 777 /tmp/mangohud_logs/*
          ls -l /tmp/mangohud_logs/*

      - name: Upload benchmark to FlightlessSomething auto
        run: |
          JOBURL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          chmod +x upload.sh && ./upload.sh ${{ secrets.MYSESSION }} "$JOBURL" "${{ github.event.inputs.description }}"
