name: Benchmark

on:
  workflow_dispatch:
    inputs:
      benchmark_file:
        description: 'Select benchmark definition file'
        required: true
        default: 'all_idle.yml'
        type: choice
        options:
          - all_busy.yml
          - erkexzcx.yml
          - all_idle.yml
          - arighi1.yml
          - arighi2.yml
          - last_commits.yml
          - specific_commits.yml

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:
      - uses: actions/checkout@v4

      - name: Perform benchmark
        run: |
          source env.sh
          chmod +x benchmark.sh
          ./benchmark.sh "benchmarks/${{ github.event.inputs.benchmark_file }}"

      - name: Upload benchmark to FlightlessSomething auto
        run: |
          source env.sh
          chmod +x upload.sh && ./upload.sh ${{ secrets.MYSESSION }} "$JOBURL" "${{ github.event.inputs.description }}"
        env:
          MYSESSION: ${{ secrets.MYSESSION }}
          JOB_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
