name: Benchmark CP2077

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    steps:

      - name: Check if Cyberpunk 2077 is not running
        run: pgrep -f 'Cyberpunk2077.exe' > /dev/null

      - name: Unfreeze the game
        run: sudo kill -CONT $(pgrep -f 'Cyberpunk2077.exe')

      - name: Ensure dotool pipe is setup
        run: |
          sudo -u deck systemctl --user start dotoold.service
          sudo chmod 777 /tmp/dotool-pipe

###########################################################################

      - name: Test dotool
        run: |
          # Cleanup
          sudo rm -f /home/deck/mangohud_logs/*

          # Wake up from sleep (e.g. screen is off)
          echo mousemove 2500 0 | dotoolc
          sleep 1

          # Do MangoHud benchmark
          echo keydown shift+f2 | dotoolc && sleep 0.2 && echo keyup shift+f2 | dotoolc # Start recording
          for i in {1..50}; do echo mousemove 2500 0 | dotoolc; sleep 0.2; done
          echo keydown shift+f2 | dotoolc && sleep 0.2 && echo keyup shift+f2 | dotoolc # Stop recording

          # Show what is recorded
          sudo rm -f /home/deck/mangohud_logs/*summary.csv
          sudo ls -l /home/deck/mangohud_logs/

###########################################################################

      - name: Freeze the game
        run: sudo kill -STOP $(pgrep -f 'Cyberpunk2077.exe')
