name: Do ydotool test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, steam-deck]
    env:
      YDOTOOL_SOCKET: /run/user/1000/.ydotool_socket
    steps:
      - name: Ensure ydotool socket is accessible
        run: |
          sudo chmod +x /run/user/1000
          sudo chmod 777 /run/user/1000/.ydotool_socket
      
      - name: Run ydotool command
        run: ydotool mousemove 2500 0
